### PR TITLE
Added Japanese2

### PR DESCRIPTION
**Pull request by memakura**
Added another Japanese translation for kids.

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thanks for the changes.

**Comment by memakura** [comment]
Thanks! and my apologies for the unnecessary pyc file.

**Comment by MrYsLab** [comment]
No problem about the pyc - it was easy enough to remove. Thanks again.

**Comment by japonophile** [comment]
@memakura さん、ありがとうございます！
Thank you!  This translation is much simpler and sounds more natural than mine.
I'm fine to just replace the old one with this one. :)

**Comment by MrYsLab** [comment]
We can leave both and let the user decide. What are your thoughts?

**Comment by memakura** [comment]
Leaving both is fine with me. In case the replacement, it is better to keep current xlate.cfg so that previous scratch codes can also be used.

**Comment by MrYsLab** [comment]
I agree. This is not only less work, but maintains compatibility for previous saved projects.

**Pull request merged**
